import { existsSync } from 'fs';
import { execFileSync } from 'child_process';
import path from 'path';
import { fileURLToPath } from 'url';

/**
 * Builds the WebAssembly packages only when they are missing.
 *
 * Both `wasm-crate/pkg` and `wasm-crate-x509/pkg` are generated by wasm-pack and
 * are not tracked by git, so a fresh clone has no wasm to import and `npm run
 * dev` would fail. This guard runs from the `predev` hook: on a warm tree it
 * does nothing (dev server starts instantly), on a fresh clone it runs
 * `npm run wasm` once.
 */
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

const ARTIFACTS = [
  'wasm-crate/pkg/uuidhash_wasm_bg.wasm',
  'wasm-crate-x509/pkg/uuidhash_x509_wasm_bg.wasm',
];

const missing = ARTIFACTS.filter((artifact) => !existsSync(path.join(ROOT, artifact)));

if (missing.length === 0) {
  process.exit(0);
}

console.log(`[ensure-wasm] missing ${missing.join(', ')} — building with wasm-pack...`);

try {
  execFileSync(process.platform === 'win32' ? 'npm.cmd' : 'npm', ['run', 'wasm'], {
    cwd: ROOT,
    stdio: 'inherit',
  });
} catch {
  console.error(
    '[ensure-wasm] wasm-pack build failed. Install Rust and wasm-pack first:\n' +
      '  https://rustup.rs  /  cargo install wasm-pack'
  );
  process.exit(1);
}
